version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOPPLER_TOKEN: "${DOPPLER_TOKEN}"
    command: doppler run -- npm start
    ports:
      - "3000:3000"
