services:
  - name: my-dockerized-app
    type: web
    env: docker
    region: us-central
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
